services:
  postgres:
    image: postgres
    container_name: caster-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  postgres_data:
